### ISSUE TITLE
Use the Csv-importer for geometries

### ISSUE THREAD

**Issue by Devmaticz** [pelias/csv-importer#12] opened 2019-01-22 22:08 UTC
Hello,

Is it possible to use the csv importer to grab geometries that can be used in PIP-service ?

Thank you

**Comment by orangejulius** [comment] 2019-01-25 17:42
Dupe of https://github.com/pelias/whosonfirst/issues/418. Bringing custom geometries into Pelias in general is on the road map, but a ways off.

**Closed by orangejulius** 2019-01-25 17:42 UTC
